version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_recipe_sharing
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:  root_password
      MYSQL_DATABASE: recipe_sharing
      MYSQL_USER: viniciussantos
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring_boot_app
#    restart: no
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    networks:
#      - app-network




volumes:
  db-data:

networks:
  app-network:
    driver: bridge